### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by rbraeunlich** [daviddenton/databob.kotlin#2]
Hi @daviddenton 
since JCenter is deprecated and the last version that can be found there still depends on "funktionale", it would be great if you could publish this library to Maven Central.
I saw that you published some versions to GitHub packages, but that doesn't allow anonymous access, which makes it very impractical.
Since your other projects like http4k are also on Maven Central I suppose it won't be too much of a problem for you to publish this project there, too.
Cheers,
Ronny

**Comment by daviddenton** [comment]
When jcenter retirement was announced, I decided not to bother migrating this to maven and tbh I doubt I'll get time or motivation to do so. 

However - you should probably check out migrating to fabrikate4k from forkhandles project as is the natural successor to databob (and also maintained and has a very similar interface).

**Comment by rbraeunlich** [comment]
Ok, then thanks for the recommendation!
